version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diploma_checker_app
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app